/* Decompiler 0ms, total 88ms, lines 81 */
package com.genesyslab.mm.bpr.extensions.wsextension;

class PackageConstants {
   static final String _EXTENSION_NAME_ = "BPR_WS_Extension";
   static final String _STAT_TYPE_NAME_ = "BPR WS Result";
   static final String _STAT_TYPE_DESCRIPTION_ = "BPR - WS Result.";
   static final String _EXTENSION_JAR_FILE_ = "java-extension-jar";
   static final String _JDBC_DRIVER_ = "jdbc-driver";
   static final String _JDBC_URL_ = "jdbc-url";
   static final String _JDBC_UNAME_ = "user";
   static final String _JDBC_PASSWORD = "password";
   static final String _JDBC_RECONNECTION_TIMEOUT_ = "reconnection-timeout";
   static final String _TENANT_ID_LIST = "tenant-ids";
   static final String _VERBOSE_ = "verbose";
   static final String _TENANT_DELIMITERS_ = "=,;";
   static final String _JDBC_DRIVER_MSSQL_ = "com.inet.tds.TdsDriver";
   static final String _JDBC_DRIVER_ORACLE_ = "com.inet.ora.OraDriver";
   static final String _JDBC_DRIVER_DB2_ = "com.ibm.db2.jcc.DB2Driver";
   static final String _SELECT_CONDITION_ = "sel-condition";
   static final String _SELECT_SOURCE_ = "sel-source";
   static final String _SELECT_VALUE_ = "sel-value";
   static final String _SELECT_SOURCE_DEFAULT_ = "interactions";
   static final String _SELECT_VALUE_DEFAULT_ = "count(*)";
   static final String _FILTER_KEY_ = "Filter";
   static final String _FILTER_QUALIFIER_ = "sql_select";
   static final String _FILTER_START_ = "WHERE=";
   static final String _SELECT_CLAUSE_ = "select ";
   static final String _FROM_CLAUSE_ = " from ";
   static final String _WHERE_CLAUSE_ = " where tenant_id=";
   static final String _NEW_WHERE_CLAUSE_ = " where ";
   static final String _QUEUE_CLAUSE_ = " and queue='";
   static final String _LINKING_AND_CLAUSE_ = " and ";
   static final int _RECONNECTION_TIMEOUT_DEFAULT = 10000;
   static final int _THREAD_INTERRRUPTION_JOIN_TIME_ = 10000;
   static final String _OPTA_DISCONNECTION_STATE_ = "08S01";
   static final String _DATE_TIME_FORMAT_ = "yyyy-MM-dd HH:mm:ss";
   static final String _DEFAULT_COLUMN_NAME_ = "dbid";
   static final String _DEFAULT_COLUMN_NAME_TENANT_ = "tenant_id";
   static final String _DEFAULT_COLUMN_NAME_QUEUE_ = "queue";
   static final String _DEFAULT_COLUMN_NAME_CAMPAIGN_OBJECTS_ = "name";
   static final String _COLUMN_DATA_NAME_ = "name";
   static final String _COLUMN_DATA_DBID_ = "dbid";
   static final String _EMPTY_DBID_ = "0";
   static final String _OPTION_USE_TENANT_NAME_ = "use-tenant";
   static final String _COLUMN_OPTION_NAME_HEADER_ = "column-name-";
   static final String _DATA_OPTION_NAME_HEADER_ = "data-type-";
   static final String _STAT_OBJECT_NAME_AGENT_ = "agent";
   static final String _STAT_OBJECT_NAME_PLACE_ = "place";
   static final String _STAT_OBJECT_NAME_GROUPAGENTS_ = "agent-group";
   static final String _STAT_OBJECT_NAME_GROUPPLACES_ = "place-group";
   static final String _STAT_OBJECT_NAME_ROUTEPOINT_ = "routepoint";
   static final String _STAT_OBJECT_NAME_QUEUE_ = "queue";
   static final String _STAT_OBJECT_NAME_GROUPQUEUES_ = "queue-group";
   static final String _STAT_OBJECT_NAME_SWITCH_ = "switch";
   static final String _STAT_OBJECT_NAME_REGDN_ = "regdn";
   static final String _STAT_OBJECT_NAME_CAMPAIGN_ = "campaign";
   static final String _STAT_OBJECT_NAME_CAMPAIGNGROUP_ = "campaign-group";
   static final String _STAT_OBJECT_NAME_CALLINGLIST_ = "calling-list";
   static final String _STAT_OBJECT_NAME_CAMPAIGNCALLINGLIST_ = "campaign-calling-list";
   static final String _STAT_OBJECT_NAME_TENANT_ = "tenant";
   static final String _STAT_OBJECT_NAME_STAGING_AREA_ = "staging-area";
   static final String _STAT_OBJECT_NAME_ROUTING_STRATEGY_ = "routing-strategy";
   static final String _STAT_OBJECT_PRINT_NAME_AGENT_ = "Agent";
   static final String _STAT_OBJECT_PRINT_NAME_PLACE_ = "Place";
   static final String _STAT_OBJECT_PRINT_NAME_GROUPAGENTS_ = "GroupAgents";
   static final String _STAT_OBJECT_PRINT_NAME_GROUPPLACES_ = "GroupPlaces";
   static final String _STAT_OBJECT_PRINT_NAME_ROUTEPOINT_ = "RoutePoint";
   static final String _STAT_OBJECT_PRINT_NAME_QUEUE_ = "Queue";
   static final String _STAT_OBJECT_PRINT_NAME_GROUPQUEUES_ = "GroupQueues";
   static final String _STAT_OBJECT_PRINT_NAME_SWITCH_ = "Switch";
   static final String _STAT_OBJECT_PRINT_NAME_REGDN_ = "RegDN";
   static final String _STAT_OBJECT_PRINT_NAME_CAMPAIGN_ = "Campaign";
   static final String _STAT_OBJECT_PRINT_NAME_CAMPAIGNGROUP_ = "CampaignGroup";
   static final String _STAT_OBJECT_PRINT_NAME_CALLINGLIST_ = "CallingList";
   static final String _STAT_OBJECT_PRINT_NAME_CAMPAIGNCALLINGLIST_ = "CampaignCallingList";
   static final String _STAT_OBJECT_PRINT_NAME_TENANT_ = "Tenant";
   static final String _STAT_OBJECT_PRINT_NAME_STAGING_AREA_ = "StagingArea";
   static final String _STAT_OBJECT_PRINT_NAME_ROUTING_STRATEGY_ = "RoutingStrategy";
   static final int _TO_STRING_BUFFER_SIZE_ = 1024;
}
